services:
  bot:
    build:
      context: .
    command: thesteambot.bot
    develop:
      watch:
        - path: packages/bot/
          action: rebuild
    env_file:
      - .env
      - .env.bot
    # restart: unless-stopped
  web:
    build:
      context: .
    command: thesteambot.web
    develop:
      watch:
        - path: packages/web/
          action: rebuild
    env_file:
      - .env
      - .env.web
    ports:
      - 2500:8000
    # restart: unless-stopped
