services:
  bot:
    build:
      dockerfile: packages/bot/Dockerfile
    develop:
      watch:
        - path: packages/bot/src/
          action: rebuild
        - path: packages/bot/pyproject.toml
          action: rebuild
    # restart: unless-stopped
  web:
    build:
      dockerfile: packages/web/Dockerfile
    develop:
      watch:
        - path: packages/web/src/
          action: rebuild
        - path: packages/web/pyproject.toml
          action: rebuild
    # restart: unless-stopped
