services:
  bot:
    build:
      context: .
    command: thesteambot.bot
    develop:
      watch:
        - path: packages/bot/
          action: rebuild
    # restart: unless-stopped
  web:
    build:
      context: .
    command: thesteambot.web
    develop:
      watch:
        - path: packages/web/
          action: rebuild
    # restart: unless-stopped
