services:
  bot:
    build:
      context: .
    command: thesteambot.bot
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    develop:
      watch:
        - path: src/thesteambot/
          ignore:
            - '**/static/'
            - '**/templates/'
          action: rebuild
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:?}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET:?}
      DOMAIN: ${DOMAIN:?}
      DEBUG: ${DEBUG:?}
      BOT_EXTENSIONS: ${BOT_EXTENSIONS}
      BOT_TOKEN: ${BOT_TOKEN:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_USER: ${DB_USER:?}
      DB_DATABASE: ${DB_DATABASE:?}
      DB_PORT: ${DB_PORT:?}
    # restart: unless-stopped
  db:
    image: postgres:18
    environment:
      # Initialization
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_DB: ${DB_DATABASE:?}
      # Healthcheck
      PGPORT: ${DB_PORT:?}
      PGPASSWORD: ${DB_PASSWORD:?}
      PGUSER: ${DB_USER:?}
      PGDATABASE: ${DB_DATABASE:?}
    expose:
      - ${DB_PORT:?}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 10s
      start_interval: 1s
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
  db-migrate:
    build:
      context: .
    command: thesteambot.db.migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: ${DEBUG:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_USER: ${DB_USER:?}
      DB_DATABASE: ${DB_DATABASE:?}
      DB_PORT: ${DB_PORT:?}
  web:
    build:
      context: .
    command: thesteambot.web
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    develop:
      watch:
        - path: src/thesteambot/web/static/
          target: /src/thesteambot/web/static/
          action: sync
        - path: src/thesteambot/web/templates/
          target: /src/thesteambot/web/templates/
          action: sync
        - path: src/thesteambot/
          ignore:
            - '**/static/'
            - '**/templates/'
          action: rebuild
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:?}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET:?}
      DOMAIN: ${DOMAIN:?}
      DEBUG: ${DEBUG:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_USER: ${DB_USER:?}
      DB_DATABASE: ${DB_DATABASE:?}
      DB_PORT: ${DB_PORT:?}
      WEB_SECRET_KEY: ${WEB_SECRET_KEY:?}
    ports:
      - 2500:8000
    # restart: unless-stopped

volumes:
  db-data:
