services:
  bot:
    build:
      dockerfile: bot/Dockerfile
    develop:
      watch:
        - path: bot/src/
          action: rebuild
        - path: bot/pyproject.toml
          action: rebuild
    # restart: unless-stopped
  web:
    build:
      dockerfile: web/Dockerfile
    develop:
      watch:
        - path: web/src/
          action: rebuild
        - path: web/pyproject.toml
          action: rebuild
    # restart: unless-stopped
